import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import Footer from '@/components/layout/Footer'

const roboto = Roboto({ subsets: ['latin'],weight:["300","400","700"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
         <main className='max-w-4xl mx-auto py-4'>
         <Header/>
         {children}
         <Footer/>
         </main>
        </body>
    </html>
  )
}
